/*
 * Contratos API
 *
 * API de Contratos
 *
 * OpenAPI spec version: 1.0.0
 * Contact: michael.costa@localiza.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class AdminsApiController : ControllerBase
    { 
        /// <summary>
        /// adiciona um contrato
        /// </summary>
        /// <remarks>adiciona um contrato à reserva</remarks>
        /// <param name="reserva">Contrato a adicionar</param>
        /// <response code="201">Contrato criado</response>
        /// <response code="400">entrada inválida, objeto inválido</response>
        /// <response code="409">um contrato com esses dados já existe</response>
        [HttpPost]
        [Route("/michaelcosta/Contratos/1.0.0/carros")]
        [ValidateModelState]
        [SwaggerOperation("AdicionarContrato")]
        public virtual IActionResult AdicionarContrato([FromBody]Contrato reserva)
        { 
            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201);

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);

            //TODO: Uncomment the next line to return response 409 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(409);


            throw new NotImplementedException();
        }
    }
}
