/*
 * Carros API
 *
 * API de Carros
 *
 * OpenAPI spec version: 1.0.0
 * Contact: michael.costa@localiza.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Carro : IEquatable<Carro>
    { 
        /// <summary>
        /// Gets or Sets Placa
        /// </summary>
        [Required]
        [DataMember(Name="placa")]
        public string Placa { get; set; }

        /// <summary>
        /// Gets or Sets Descricao
        /// </summary>
        [Required]
        [DataMember(Name="descricao")]
        public string Descricao { get; set; }

        /// <summary>
        /// Gets or Sets Loja
        /// </summary>
        [Required]
        [DataMember(Name="loja")]
        public string Loja { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Carro {\n");
            sb.Append("  Placa: ").Append(Placa).Append("\n");
            sb.Append("  Descricao: ").Append(Descricao).Append("\n");
            sb.Append("  Loja: ").Append(Loja).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Carro)obj);
        }

        /// <summary>
        /// Returns true if Carro instances are equal
        /// </summary>
        /// <param name="other">Instance of Carro to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Carro other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Placa == other.Placa ||
                    Placa != null &&
                    Placa.Equals(other.Placa)
                ) && 
                (
                    Descricao == other.Descricao ||
                    Descricao != null &&
                    Descricao.Equals(other.Descricao)
                ) && 
                (
                    Loja == other.Loja ||
                    Loja != null &&
                    Loja.Equals(other.Loja)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Placa != null)
                    hashCode = hashCode * 59 + Placa.GetHashCode();
                    if (Descricao != null)
                    hashCode = hashCode * 59 + Descricao.GetHashCode();
                    if (Loja != null)
                    hashCode = hashCode * 59 + Loja.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Carro left, Carro right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Carro left, Carro right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
