/*
 * Carros API
 *
 * API de Carros
 *
 * OpenAPI spec version: 1.0.0
 * Contact: michael.costa@localiza.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

using Microsoft.Extensions.Caching.Memory;
using System.Linq;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DevelopersApiController : ControllerBase
    {
        IMemoryCache cache = null;

        /// <summary>
        /// 
        /// </summary>
        /// <param name="cache"></param>
        public DevelopersApiController(IMemoryCache cache)
        {
            this.cache = cache;
        }
        /// <summary>
        /// Busca carros
        /// </summary>
        /// <remarks>Retorna lista de carros disponíveis </remarks>
        /// <param name="loja">código da loja (opcional)</param>
        /// <param name="placa">placa do carro(opcional)</param>
        /// <response code="200">resultados conforme critérios informados</response>
        /// <response code="400">entrada inválida</response>
        #nullable enable
        [HttpGet]
        [Route("/michaelcosta/Carros/1.0.0/carros")]
        [ValidateModelState]
        [SwaggerOperation("BuscarCarros")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Carro>), description: "resultados conforme critérios informados")]
        public virtual IActionResult BuscarCarros([FromQuery]string? loja, [FromQuery] string? placa)
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...

            //System.Runtime.Caching.MemoryCache cache = new System.Runtime.Caching.MemoryCache("carros");

            List<Carro> lista = (List<Carro>)cache.Get("ListaCarros");
            if (lista == null)
            {
                lista = Startup.GerarMocCarros();
                cache.Set<System.Collections.Generic.List<Models.Carro>>("ListaCarros", lista, DateTimeOffset.Now.AddMinutes(10.0));
            }
            //return StatusCode(200, lista);


            if (loja != null)
            {
                var result = from l in lista
                             where l.Loja == loja
                             select l;
                if (result.Any())
                {

                    return StatusCode(200, result);
                }
                else
                {
                    return StatusCode(404);
                }
            } else if (placa != null)
            {
                var result = from l in lista
                             where l.Placa == placa
                             select l;
                if (result.Any())
                {

                    return StatusCode(200, result);
                }
                else
                {
                    return StatusCode(404);
                }
            }
            else
            {
                return StatusCode(200, lista);
            }
        }
    }
}
