/*
 * Reservas API
 *
 * API de Reservas
 *
 * OpenAPI spec version: 1.0.0
 * Contact: michael.costa@localiza.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Reserva : IEquatable<Reserva>
    { 
        /// <summary>
        /// Gets or Sets Localizador
        /// </summary>
        [DataMember(Name="localizador")]
        public string Localizador { get; set; }

        /// <summary>
        /// Gets or Sets Placa
        /// </summary>
        [Required]
        [DataMember(Name="placa")]
        public string Placa { get; set; }

        /// <summary>
        /// Gets or Sets IdCLiente
        /// </summary>
        [Required]
        [DataMember(Name="idCliente")]
        public int? IdCliente { get; set; }

        /// <summary>
        /// Gets or Sets Loja
        /// </summary>
        [DataMember(Name="loja")]
        public string Loja { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets IdPagamento
        /// </summary>
        [DataMember(Name="idPagamento")]
        public int? IdPagamento { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Reserva {\n");
            sb.Append("  Localizador: ").Append(Localizador).Append("\n");
            sb.Append("  Placa: ").Append(Placa).Append("\n");
            sb.Append("  IdCliente: ").Append(IdCliente).Append("\n");
            sb.Append("  Loja: ").Append(Loja).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  IdPagamento: ").Append(IdPagamento).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Reserva)obj);
        }

        /// <summary>
        /// Returns true if Reserva instances are equal
        /// </summary>
        /// <param name="other">Instance of Reserva to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Reserva other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Localizador == other.Localizador ||
                    Localizador != null &&
                    Localizador.Equals(other.Localizador)
                ) && 
                (
                    Placa == other.Placa ||
                    Placa != null &&
                    Placa.Equals(other.Placa)
                ) && 
                (
                    IdCliente == other.IdCliente ||
                    IdCliente != null &&
                    IdCliente.Equals(other.IdCliente)
                ) && 
                (
                    Loja == other.Loja ||
                    Loja != null &&
                    Loja.Equals(other.Loja)
                ) && 
                (
                    Status == other.Status ||
                    Status != null &&
                    Status.Equals(other.Status)
                ) && 
                (
                    IdPagamento == other.IdPagamento ||
                    IdPagamento != null &&
                    IdPagamento.Equals(other.IdPagamento)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Localizador != null)
                    hashCode = hashCode * 59 + Localizador.GetHashCode();
                    if (Placa != null)
                    hashCode = hashCode * 59 + Placa.GetHashCode();
                    if (IdCliente != null)
                    hashCode = hashCode * 59 + IdCliente.GetHashCode();
                    if (Loja != null)
                    hashCode = hashCode * 59 + Loja.GetHashCode();
                    if (Status != null)
                    hashCode = hashCode * 59 + Status.GetHashCode();
                    if (IdPagamento != null)
                    hashCode = hashCode * 59 + IdPagamento.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Reserva left, Reserva right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Reserva left, Reserva right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
